# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ScrollYearViewDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'CustomScrollYearView',:git => 'https://github.com/FelixYin66/ScrollYearView.git'

end
